WIP - Added health check
PowerDNS-Admin/PowerDNS-Admin pull request #1172
Opened 2022-04-18 09:05 UTC by RGanor

Add health check API that also check the authoritative api.

2022-04-26 18:35 UTC, jbe-dw reviewed
I took time to give my opinion.

Regards

2022-04-26 18:35 UTC, jbe-dw commented on powerdnsadmin/routes/api.py
> +        return make_response("bad", 503)
I'm not sure if we should use 503 here, it's not PDA failing but the backend

2022-05-06 21:40 UTC, jbe-dw commented on powerdnsadmin/routes/api.py
> +        return make_response("bad", 503)
This piece of code is already implemented in get_domain_info(). Did you try the code I posted ?

2022-05-15 12:25 UTC, RGanor commented
@jbe-dw I have updated the code to use the domain model function and added authentication requirement.
Now, after we removed the `/ping` authentication, I think it make sense for this function to be more robust in its check, but because it is querying the pdns auth api (which can be resource intensive some time), the authentication is required to protect this endpoint.
I think that `/ping` and `/api/v1/health` should co-exist, each with different propose.

2022-05-22 15:58 UTC, jbe-dw requested changes
As we discussed, i'm waiting for an alternative message if there is no domain to query

2022-05-22 16:00 UTC, RGanor commented
Hey @jbe-dw , thanks for bumping this up. I will be able fix this soon.

2022-05-23 18:18 UTC, jbe-dw approved these changes

2022-05-23 18:18 UTC, merged